import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Inbox,Send,PenLine,Search,ChevronLeft,Mail,MailOpen,RefreshCw,Sparkles,Paperclip,Reply,LogOut,Command} from 'lucide-react';
import './styles.css';

const API='http://localhost:8000/api';
const api=async(path,opt={})=>{const r=await fetch(API+path,{headers:{'Content-Type':'application/json'},...opt}); if(!r.ok) throw new Error(await r.text()); return r.json()};

function App(){
 const [view,setView]=useState('inbox'),[emails,setEmails]=useState([]),[selected,setSelected]=useState(null),[loading,setLoading]=useState(false),[connected,setConnected]=useState(false),[search,setSearch]=useState('');
 const [compose,setCompose]=useState({to:'',subject:'',body:'',replyTo:null}),[assistant,setAssistant]=useState([]),[prompt,setPrompt]=useState('');
 const [filters,setFilters]=useState({unread:false,days:''});
 const label=view==='sent'?'SENT':'INBOX';
 const load=async(q='')=>{setLoading(true);try{const r=await api(`/emails?label=${label}&q=${encodeURIComponent(q)}`);setEmails(r.emails)}catch(e){setAssistant(x=>[...x,{role:'assistant',text:'Connect Gmail first, then I can load your mail.'}])}finally{setLoading(false)}};
 useEffect(()=>{api('/auth/status').then(r=>setConnected(r.connected));load()},[view]);
 useEffect(()=>{if(!connected)return; const ws=new WebSocket('ws://localhost:8000/api/ws'); ws.onmessage=(e)=>{try{const m=JSON.parse(e.data); if(m.type==='mail_changed') load(search)}catch{}}; return()=>ws.close()},[connected,view,search]);
 const connect=async()=>{try{await api('/auth/connect',{method:'POST'});setConnected(true);load()}catch(e){alert(e.message)}};
 const open=async(e)=>{const r=await api(`/emails/${e.id}`);setSelected(r);setView('detail')};
 const send=async()=>{if(!compose.to)return;await api('/send',{method:'POST',body:JSON.stringify(compose)});setCompose({to:'',subject:'',body:'',replyTo:null});setView('inbox');load()};
 const runAssistant=async()=>{if(!prompt.trim())return;const text=prompt;setPrompt('');setAssistant(x=>[...x,{role:'user',text}]);try{const cmd=await api('/assistant',{method:'POST',body:JSON.stringify({message:text,context:{view,selectedEmail:selected}})});await execute(cmd,text)}catch(e){setAssistant(x=>[...x,{role:'assistant',text:'I could not execute that request.'}])}};
 const execute=async(cmd,text)=>{
  if(cmd.action==='compose'){setCompose({to:cmd.args?.to||'',subject:cmd.args?.subject||'',body:cmd.args?.body||'',replyTo:null});setView('compose');setAssistant(x=>[...x,{role:'assistant',text:'I opened Compose and filled the fields for you. Review and send when ready.'}]);return}
  if(cmd.action==='reply'){if(!selected){setAssistant(x=>[...x,{role:'assistant',text:'Open an email first, then say “reply to this”.'}]);return}setCompose({to:selected.sender,subject:selected.subject?.startsWith('Re:')?selected.subject:'Re: '+selected.subject,body:cmd.args?.body||'',replyTo:selected.id});setView('compose');setAssistant(x=>[...x,{role:'assistant',text:'Reply draft opened with the current email as context.'}]);return}
  if(cmd.action==='open'){const q=cmd.args?.query||text;const r=await api(`/emails?label=INBOX&q=${encodeURIComponent(q.replace(/^open\s+/i,''))}`);if(r.emails[0]){await open(r.emails[0]);setAssistant(x=>[...x,{role:'assistant',text:'Opened the matching email.'}])}else setAssistant(x=>[...x,{role:'assistant',text:'I could not find a matching email.'}]);return}
  if(cmd.action==='filter'||cmd.action==='search'){setView('inbox');const q=cmd.args?.query||text;setSearch(q);const r=await api(`/emails?label=INBOX&q=${encodeURIComponent(q)}`);setEmails(r.emails);setAssistant(x=>[...x,{role:'assistant',text:`Showing ${r.emails.length} matching emails in the main view.`}]);return}
 };
 const filtered=useMemo(()=>emails.filter(e=>!filters.unread||e.unread),[emails,filters]);
 return <div className="app">
  <aside className="sidebar"><div className="brand"><div className="brand-mark"><Sparkles size={17}/></div><span>Nebula Mail</span></div>
   <button className="compose-btn" onClick={()=>setView('compose')}><PenLine size={18}/> Compose</button>
   <nav><button className={view==='inbox'?'active':''} onClick={()=>{setView('inbox');setSelected(null)}}><Inbox/>Inbox<span>{emails.filter(e=>e.unread).length||''}</span></button><button className={view==='sent'?'active':''} onClick={()=>{setView('sent');setSelected(null)}}><Send/>Sent</button></nav>
   <div className="sidebar-bottom"><button onClick={connect} className="account"><div className="avatar">G</div><div><b>{connected?'Gmail connected':'Connect Gmail'}</b><small>{connected?'Real mailbox':'OAuth required'}</small></div></button></div>
  </aside>
  <main className="main"><header className="topbar"><div><h1>{view==='sent'?'Sent':view==='compose'?'Compose':view==='detail'?'Email':'Inbox'}</h1><p>{connected?'Synced with Gmail':'Connect Gmail to load real emails'}</p></div><div className="top-actions"><div className="search"><Search size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>e.key==='Enter'&&load(search)} placeholder="Search mail"/></div><button className="icon-btn" onClick={()=>load(search)}><RefreshCw size={17}/></button></div></header>
   {view==='compose'?<Compose compose={compose} setCompose={setCompose} send={send} cancel={()=>setView('inbox')}/>:view==='detail'&&selected?<Detail email={selected} back={()=>setView('inbox')} reply={()=>{setCompose({to:selected.sender,subject:'Re: '+selected.subject,body:'',replyTo:selected.id});setView('compose')}}/>:<InboxView emails={filtered} loading={loading} open={open} filters={filters} setFilters={setFilters}/>} 
  </main>
  <aside className="assistant"><div className="assistant-head"><div><div className="eyebrow"><Command size={13}/> AI CONTROL</div><h2>Mail Copilot</h2></div><span className="live-dot">LIVE</span></div><div className="assistant-body">{assistant.length===0&&<div className="starter"><Sparkles size={28}/><h3>Control your inbox</h3><p>Ask me to compose, search, filter, open or reply. I will update the UI instead of only replying in chat.</p><div className="suggestions"><button onClick={()=>setPrompt('Show me emails from the last 10 days')}>Show last 10 days</button><button onClick={()=>setPrompt('Show only unread emails from this week')}>Unread this week</button><button onClick={()=>setPrompt('Reply to this')}>Reply to this</button></div></div>}{assistant.map((m,i)=><div key={i} className={'msg '+m.role}><div className="msg-label">{m.role==='user'?'You':'Copilot'}</div><div>{m.text}</div></div>)}</div><div className="assistant-input"><textarea value={prompt} onChange={e=>setPrompt(e.target.value)} onKeyDown={e=>e.key==='Enter'&&!e.shiftKey&&(e.preventDefault(),runAssistant())} placeholder="Tell me what to do..."/><button onClick={runAssistant}><Sparkles size={17}/></button></div></aside>
 </div>
}
function InboxView({emails,loading,open,filters,setFilters}){return <section className="content"><div className="filterbar"><span>{loading?'Syncing…':`${emails.length} emails`}</span><div><label><input type="checkbox" checked={filters.unread} onChange={e=>setFilters({...filters,unread:e.target.checked})}/> Unread</label><select value={filters.days} onChange={e=>setFilters({...filters,days:e.target.value})}><option value="">Any date</option><option value="10">Last 10 days</option><option value="7">Last 7 days</option><option value="30">Last 30 days</option></select></div></div><div className="mail-list">{emails.map(e=><button className={'mail-row '+(e.unread?'unread':'')} key={e.id} onClick={()=>open(e)}><div className="sender">{e.sender.split('<')[0].trim()}</div><div className="subject">{e.subject}<span> — {e.snippet}</span></div><time>{e.date}</time></button>)}{!loading&&emails.length===0&&<div className="empty"><MailOpen size={36}/><h3>No messages</h3><p>Try another search or connect your Gmail account.</p></div>}</div></section>}
function Compose({compose,setCompose,send,cancel}){return <section className="compose-card"><div className="compose-head"><span>New message</span><button onClick={cancel}>×</button></div><input value={compose.to} onChange={e=>setCompose({...compose,to:e.target.value})} placeholder="To"/><input value={compose.subject} onChange={e=>setCompose({...compose,subject:e.target.value})} placeholder="Subject"/><textarea value={compose.body} onChange={e=>setCompose({...compose,body:e.target.value})} placeholder="Write your message…"/><div className="compose-foot"><button className="secondary"><Paperclip size={16}/> Attach</button><button className="send-btn" onClick={send}>Send <Send size={15}/></button></div></section>}
function Detail({email,back,reply}){return <section className="detail"><button className="back" onClick={back}><ChevronLeft size={17}/> Back to inbox</button><div className="detail-card"><div className="detail-meta"><div className="avatar large">{email.sender?.[0]||'?'}</div><div><h2>{email.subject}</h2><p>{email.sender}</p><small>{email.date}</small></div></div><div className="detail-body">{email.body||email.snippet}</div><button className="reply-btn" onClick={reply}><Reply size={16}/> Reply</button></div></section>}
createRoot(document.getElementById('root')).render(<App/>);
